name: Update Docker Image using GitHub Packages

# Utiliza GH Container Registry
# https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # Push to Github Container Registry
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          version: ${{ steps.extract_branch.outputs.branch }}
          file: Dockerfile
          push: true
          tags: "ghcr.io/${{ github.repository }}:${{ steps.extract_branch.outputs.branch }}"
